export const navbarLayoutLocal = {
  MainPage: 'صفحه اصلی',
  ExpenseSettings: 'تنظیمات هزینه',
  Expense: 'هزینه',
  BaseSettings: 'تنظیمات پایه',
  Trnsfer: 'ارسال به مالی',
  Info: 'راهنما',
  More: 'سایر',
  NavbarReport: 'گزارشات',
  NavbarImportFile: 'وارد کردن فایل',
  NavbarBrand: 'ایرانیان پوشش',
  NavbarExit: 'خروج',
  NavbarRefresh: 'بازنشانی تنظیمات',
  NavAccSettings: 'تنظیمات حساب کاربری',
  NavMenuSetting: 'تنظیمات نمایشگر',
  NavMenuDark: 'تم تاریک',
  NavMenuLight: 'تم روشن',
  NavMenProfile: 'مشاهده پروفایل',
  NavMenuColorPalette: ' پالت رنگ',
  NavMenDarkPalette: 'پالت رنگ پس زمینه',
  NavMenFullscreen: 'ابعاد نمایش گر',
  NavMenuFull: 'تمام صفحه',
  NavMenuExitFull: 'خروج از تمام صفحه',
  NavTestSMS: 'تست پیام کوتاه',
  NavChangeStatus: 'تغییر وضعیت هزینه',
};
